/**
 * AI Service Module
 *
 * This module manages AI response generation.
 * Currently, it simulates realistic responses with delay and streaming chunks.
 *
 * =========================================================================
 * HOW TO CONNECT A REAL API LATER:
 * =========================================================================
 * 1. To connect OpenAI / Anthropic / Gemini:
 *    Replace the `generateAIResponse` body with a fetch to your backend endpoint:
 *    ```ts
 *    const response = await fetch('/api/chat', {
 *      method: 'POST',
 *      headers: { 'Content-Type': 'application/json' },
 *      body: JSON.stringify({ modelId, messages, prompt })
 *    });
 *    const data = await response.json();
 *    return data.reply;
 *    ```
 * 2. Or for server-sent event (SSE) streaming:
 *    Consume the stream and call `onChunk(accumulatedText)` as chunks arrive.
 * =========================================================================
 */

import { Message } from '../types';

interface GenerateOptions {
  modelId: string;
  prompt: string;
  history: Message[];
  onChunk?: (partialText: string) => void;
  signal?: AbortSignal;
}

// Sample dynamic response templates for varied simulation
function generateSimulatedResponse(prompt: string, modelId: string): string {
  const lower = prompt.toLowerCase();

  if (lower.includes('code') || lower.includes('function') || lower.includes('typescript') || lower.includes('javascript') || lower.includes('script')) {
    return `Here is an implementation tailored to your request:

\`\`\`typescript
/**
 * Processes and validates incoming data packets
 */
interface ProcessConfig {
  retries: number;
  timeoutMs: number;
  strictMode?: boolean;
}

export async function processPayload<T>(
  data: T,
  config: ProcessConfig = { retries: 3, timeoutMs: 5000 }
): Promise<{ success: boolean; data: T }> {
  console.log(\`Starting pipeline with \${config.retries} retries max...\`);
  
  // Simulated processing delay
  await new Promise((resolve) => setTimeout(resolve, 300));
  
  return {
    success: true,
    data
  };
}
\`\`\`

### Highlights
* **Type-Safe**: Uses generics \`<T>\` to preserve input data shapes.
* **Resilient**: Configurable retry intervals and timeout limits.
* **Clean Async Handling**: Returns a typed promise with structured status.

Let me know if you would like me to add automated unit tests or error boundaries!`;
  }

  if (lower.includes('table') || lower.includes('compare') || lower.includes('vs') || lower.includes('difference')) {
    return `Here is a side-by-side comparison for your analysis:

| Feature / Metric | Standard Approach | Optimized Solution |
| :--- | :--- | :--- |
| **Response Latency** | ~350ms average | < 45ms cached |
| **Memory Footprint** | Dynamic allocation | Fixed pool buffer |
| **Throughput** | 1,200 req/sec | 18,500 req/sec |
| **Complexity** | Minimal setup | Requires cache tier |

### Key Takeaways
1. **Low overhead**: Ideal for high-concurrency microservices.
2. **Predictable scaling**: Eliminates memory spikes under burst loads.
3. **Implementation effort**: Roughly 1-2 hours of integration.`;
  }

  if (lower.includes('write') || lower.includes('email') || lower.includes('draft') || lower.includes('message')) {
    return `Here is a polished draft you can use:

> **Subject:** Following up on our project milestones & next steps
>
> Hi Team,
>
> Thank you for the productive session earlier today. I wanted to share a quick summary of what we agreed upon and outline our immediate priorities for the sprint:
>
> 1. **Architecture Review**: Finalizing API contracts by Wednesday EOD.
> 2. **Component Implementation**: Delivering responsive layouts and interaction testing.
> 3. **Deployment**: Staging release on Friday morning.
>
> Please let me know if you have any questions or adjustments.
>
> Warm regards,  
> *Alex*

Feel free to tweak the tone (e.g. more casual or more formal) if you need adjustments!`;
  }

  // Default intelligent assistant response
  return `Thank you for your message! Here is a thoughtful response generated by **${modelId}**:

You asked:
> "${prompt.trim()}"

### Key Perspectives & Overview
* **Clear Structure**: Breaking complex queries into manageable, modular phases ensures clarity and execution speed.
* **Best Practices**: Adhere to clean separation of concerns, test edge cases, and maintain comprehensive documentation.
* **Future Scalability**: Building with flexibility allows seamless upgrades down the road.

If you would like to explore this in deeper detail or test specific implementations, just say the word!`;
}

/**
 * Simulates an AI call with progressive typing animation chunks.
 */
export async function generateAIResponse({
  modelId,
  prompt,
  history: _history,
  onChunk,
  signal
}: GenerateOptions): Promise<string> {
  // Initial thinking latency (600ms - 900ms)
  await new Promise((resolve) => setTimeout(resolve, 700));

  if (signal?.aborted) {
    throw new DOMException('Aborted', 'AbortError');
  }

  const fullResponse = generateSimulatedResponse(prompt, modelId);

  // If streaming callback is provided, simulate realistic word-by-word streaming
  if (onChunk) {
    const words = fullResponse.split(' ');
    let accumulated = '';

    for (let i = 0; i < words.length; i++) {
      if (signal?.aborted) {
        throw new DOMException('Aborted', 'AbortError');
      }

      accumulated += (i === 0 ? '' : ' ') + words[i];
      onChunk(accumulated);

      // Random natural typing cadence: between 15ms and 35ms per word
      const delay = Math.floor(Math.random() * 20) + 15;
      await new Promise((r) => setTimeout(r, delay));
    }
  }

  return fullResponse;
}
